export { NimerClient, type NimerClientOptions } from "./client.js";

export {
  ApiError,
  AuthenticationError,
  BudgetExceededError,
  CancelledError,
  HalalBlockedError,
  NetworkError,
  NimerError,
  NotFoundError,
  PermissionError,
  ProviderError,
  RateLimitError,
  ValidationError,
} from "./errors.js";

export { parseSseStream, parseJsonStream } from "./stream.js";
export {
  signWebhookPayload,
  verifyWebhookSignature,
  type VerifyWebhookOptions,
} from "./webhookSig.js";

export type {
  AccountUpdate,
  AnomalyEvent,
  AnthropicTool,
  ApiKey,
  ApiKeyCreated,
  AuditEvent,
  AuditQuery,
  CacheStats,
  ChatCompletionRequest,
  ChatMessage,
  ChatMode,
  ChatResponse,
  ChatResponseAuto,
  ChatResponseUltrathink,
  ChatStreamChunk,
  ChatTool,
  ChatToolCall,
  ChatToolChoice,
  CreatorStatus,
  EmbeddingInput,
  EmbeddingObject,
  EmbeddingsRequest,
  EmbeddingsResponse,
  EmbeddingsUsage,
  FeedbackCreate,
  HalalAuditEntry,
  HalalAuditList,
  ModelCatalogItem,
  ModelTier,
  Plan,
  ProviderId,
  ProviderListItem,
  TimeseriesPoint,
  TrialState,
  TrialStateStatus,
  UsageSummary,
  UserAccount,
  VirtualKey,
  VirtualKeyCreate,
  VirtualKeyCreated,
  VirtualKeyUsage,
  WebhookDelivery,
  WebhookEndpoint,
  WebhookEndpointCreate,
  WebhookEndpointUpdate,
  WebhookEndpointWithSecret,
} from "./types.js";
